import type { Category, Drink } from "./supabase/queries";

export const INITIAL_CATEGORIES: Category[] = [
  { id: "cat-1", name: "Aguardientes", slug: "aguardientes", created_at: new Date().toISOString() },
  { id: "cat-2", name: "Cócteles", slug: "cocteles", created_at: new Date().toISOString() },
  { id: "cat-3", name: "Cervezas", slug: "cervezas", created_at: new Date().toISOString() },
  { id: "cat-4", name: "Whisky", slug: "whisky", created_at: new Date().toISOString() },
  { id: "cat-5", name: "Tequila", slug: "tequila", created_at: new Date().toISOString() },
  { id: "cat-6", name: "Botellas", slug: "botellas", created_at: new Date().toISOString() },
];

export const INITIAL_DRINKS: Drink[] = [
  {
    id: "drink-1",
    name: "Antioqueño Azul",
    slug: "antioqueno-azul-750ml",
    category_id: "cat-1",
    brand: "Sin Azúcar",
    volume: "750ml",
    price: 180000,
    description: "Aguardiente tradicional de Antioquia, formulado sin azúcar con notas puras y equilibradas de anís estrellado.",
    image_url: "https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=400&q=80",
    is_available: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    categories: { id: "cat-1", name: "Aguardientes", slug: "aguardientes" },
  },
  {
    id: "drink-2",
    name: "Aguardiente Amarillo",
    slug: "aguardiente-amarillo-manzanares-750ml",
    category_id: "cat-1",
    brand: "Manzanares",
    volume: "750ml",
    price: 210000,
    description: "El pionero de los aguardientes en Colombia. Con su color ámbar natural y sabor equilibrado, es la elección perfecta para una noche VIP inolvidable.",
    image_url: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=400&q=80",
    is_available: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    categories: { id: "cat-1", name: "Aguardientes", slug: "aguardientes" },
  },
  {
    id: "drink-3",
    name: "Gin Tonic Premium",
    slug: "gin-tonic-premium-bosque-de-indias",
    category_id: "cat-2",
    brand: "Bosque de Indias",
    volume: "Copa Balón",
    price: 45000,
    description: "Ginebra artesanal botánica, agua tónica premium, perfumada con frutos cítricos y bayas de enebro.",
    image_url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=400&q=80",
    is_available: true,
    is_featured: false,
    created_at: new Date().toISOString(),
    categories: { id: "cat-2", name: "Cócteles", slug: "cocteles" },
  },
  {
    id: "drink-4",
    name: "Corona Extra",
    slug: "corona-extra-355ml",
    category_id: "cat-3",
    brand: "Botella",
    volume: "355ml",
    price: 15000,
    description: "Cerveza clara mexicana con notas refrescantes de malta y lúpulo suave, servida fría con limón.",
    image_url: "https://images.unsplash.com/photo-1608270195574-8848c264a938?auto=format&fit=crop&w=400&q=80",
    is_available: true,
    is_featured: false,
    created_at: new Date().toISOString(),
    categories: { id: "cat-3", name: "Cervezas", slug: "cervezas" },
  },
  {
    id: "drink-5",
    name: "Whisky Old Parr 12 Años",
    slug: "whisky-old-parr-12-anos-750ml",
    category_id: "cat-4",
    brand: "Old Parr",
    volume: "750ml",
    price: 280000,
    description: "Whisky escocés blend añejado por 12 años. De color dorado ámbar, con aromas a frutas cítricas maduras y caramelo ahumado.",
    image_url: "https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=400&q=80",
    is_available: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    categories: { id: "cat-4", name: "Whisky", slug: "whisky" },
  },
  {
    id: "drink-6",
    name: "Buchanan's De Luxe 12",
    slug: "buchanans-de-luxe-12-750ml",
    category_id: "cat-4",
    brand: "Buchanan's",
    volume: "750ml",
    price: 290000,
    description: "Reconocido blended scotch de perfil sedoso, toques de mandarina, chocolate suave y final ahumado ligero.",
    image_url: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=400&q=80",
    is_available: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    categories: { id: "cat-4", name: "Whisky", slug: "whisky" },
  },
  {
    id: "drink-7",
    name: "Tequila Don Julio 70",
    slug: "tequila-don-julio-70-700ml",
    category_id: "cat-5",
    brand: "Don Julio",
    volume: "700ml",
    price: 450000,
    description: "Añejo cristalino filtrado en carbón para conservar la frescura del agave blanco con la riqueza compleja del añejado.",
    image_url: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=400&q=80",
    is_available: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    categories: { id: "cat-5", name: "Tequila", slug: "tequila" },
  },
  {
    id: "drink-8",
    name: "Mojito Maracuyá VIP",
    slug: "mojito-maracuya-vip",
    category_id: "cat-2",
    brand: "180° Signature",
    volume: "Copa Collins",
    price: 38000,
    description: "Ron blanco añejo, pulpa fresca de maracuyá, menta macerada, jugo de lima fresca y soda refrescante.",
    image_url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=400&q=80",
    is_available: true,
    is_featured: false,
    created_at: new Date().toISOString(),
    categories: { id: "cat-2", name: "Cócteles", slug: "cocteles" },
  },
];
